# Site settings
title: "joe's space"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sxzhou.github.io" # the base hostname & protocol for your site
github_username: sxzhou

timezone: Beijing
gems: ['jekyll-paginate']

# Build settings
highlighter: rouge
permalink: /:categories/:title/

markdown: kramdown
# markdown: redcarpet
redcarpet:
  extensions: ['fenced_code_blocks', 'tables']

paginate: 25
